### ISSUE TITLE
Re: 'Support'

### ISSUE THREAD

**Issue by alanmaddrell** [alphagov/tdt-documentation#189]
Problem with 'Support' (https://tdt-documentation.london.cloudapps.digital//support/)

This page mentions the CDDO tech writing team - not sure about the current status of this.

**Comment by lfdebrux** [comment]
Let's change 'Central Digital and Data Office (CDDO) technical writing team' to 'tech docs template working group'

**Comment by lfdebrux** [comment]
Raised a PR to fix this https://github.com/alphagov/tdt-documentation/pull/193, sorry it took so long to get around to.
