### ISSUE TITLE
Re: 'Prerequisites for Macs'

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/tdt-documentation#65]
Problem with 'Prerequisites for Macs' (https://tdt-documentation.london.cloudapps.digital//install_macs.html)

sd-community@... email no longer exists.

**Comment by bravegrape** [comment]
The page no longer links to the sd-community@... email. It was [changed to link to the GDS Web Help Desk](https://github.com/alphagov/tdt-documentation/commit/7bc4b0834c5f7c1f95e57546fc5c47ef676d5b1a) instead.
