### ISSUE TITLE
Switch to a docker-based system for preview & build

### ISSUE THREAD

**Issue by digitalronin** [alphagov/tdt-documentation#68]
The current instructions require people to install ruby and the gems before they can get started with tech docs.

IMO, a docker-based workflow would be more generally applicable (e.g. developers who have never used ruby are still fairly likely to know about docker, or to have it installed already).

The following files could be used as the basis of a preview & build workflow, without requiring users to have ruby installed locally:

https://github.com/ministryofjustice/cloud-platform-user-guide/blob/master/makefile
https://github.com/ministryofjustice/cloud-platform-user-guide/blob/master/Dockerfile

**Comment by m-green** [comment]
Thank you for raising this @digitalronin - this is also covered in https://github.com/alphagov/tdt-documentation/issues/124 so I'm consolidating into that issue. Hope that's ok.
